[ONB-70] Add disable activation link button/model to table
Woven-dojo/dojo-frontend-app-admin-portal pull request #21
Opened 2022-10-17 10:41 UTC by goktug-gurbuzturk-wp

2022-10-17 10:55 UTC, weaverjess requested changes
Will slack @goktug-gurbuzturk-wp

2022-10-17 11:13 UTC, jakub-koza-wp commented on src/components/subscriptions/buttons/DeleteActivationButton.jsx
> +        addToast('Activation link is disabled successfully.');
```suggestion
        addToast('Activation link was disabled successfully.');
```

2022-10-17 11:13 UTC, jakub-koza-wp commented on src/components/subscriptions/buttons/DeleteActivationButton.jsx
> +        title="Are you sure want to disable!"
I would suggest changing the wording a little
```suggestion
        title="Are you sure you want to disable this link?"
```

2022-10-17 11:13 UTC, jakub-koza-wp commented on src/components/subscriptions/buttons/DeleteActivationButton.jsx
> +          to continue with the disabling, please click the Disable button.
I think we can drop the last sentence. Actions seem obvious to me from just `Cancel`/`Disable` button naming.
```suggestion
          clicking the activation link in the received email. This action cannot be undone.
```

2022-10-17 14:45 UTC, weaverjess commented on src/components/subscriptions/buttons/DeleteActivationButton.jsx
> +          If you disable activation link, the user will not be able to activate the account by
"If you disable this activation link, the user will no longer be able activate their account via the activation link they were emailed. This action cannot be undone."

2022-10-17 14:46 UTC, weaverjess reviewed
Sorry, one last change on the words then this is good to go.

2022-10-17 16:45 UTC, jakub-koza-wp commented on src/components/subscriptions/buttons/DeleteActivationButton.jsx
> +          If you disable this activation link, the user will no longer be able activate
I think that `to` should still be there
```suggestion
          If you disable this activation link, the user will no longer be able to activate
```

2022-10-18 07:23 UTC, weaverjess approved these changes

2022-10-18 07:23 UTC, merged